/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as MarketRouteImport } from './routes/market'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as OpportunitiesSlugRouteImport } from './routes/opportunities.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesSlugRoute = OpportunitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OpportunitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/market': typeof MarketRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/startups': typeof StartupsRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/market': typeof MarketRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/startups': typeof StartupsRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/market': typeof MarketRoute
  '/opportunities': typeof OpportunitiesRouteWithChildren
  '/startups': typeof StartupsRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/apply'
    | '/committee'
    | '/contact'
    | '/events'
    | '/faq'
    | '/investors'
    | '/market'
    | '/opportunities'
    | '/startups'
    | '/opportunities/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/apply'
    | '/committee'
    | '/contact'
    | '/events'
    | '/faq'
    | '/investors'
    | '/market'
    | '/opportunities'
    | '/startups'
    | '/opportunities/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/apply'
    | '/committee'
    | '/contact'
    | '/events'
    | '/faq'
    | '/investors'
    | '/market'
    | '/opportunities'
    | '/startups'
    | '/opportunities/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  CommitteeRoute: typeof CommitteeRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  InvestorsRoute: typeof InvestorsRoute
  MarketRoute: typeof MarketRoute
  OpportunitiesRoute: typeof OpportunitiesRouteWithChildren
  StartupsRoute: typeof StartupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$slug': {
      id: '/opportunities/$slug'
      path: '/$slug'
      fullPath: '/opportunities/$slug'
      preLoaderRoute: typeof OpportunitiesSlugRouteImport
      parentRoute: typeof OpportunitiesRoute
    }
  }
}

interface OpportunitiesRouteChildren {
  OpportunitiesSlugRoute: typeof OpportunitiesSlugRoute
}

const OpportunitiesRouteChildren: OpportunitiesRouteChildren = {
  OpportunitiesSlugRoute: OpportunitiesSlugRoute,
}

const OpportunitiesRouteWithChildren = OpportunitiesRoute._addFileChildren(
  OpportunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  CommitteeRoute: CommitteeRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  InvestorsRoute: InvestorsRoute,
  MarketRoute: MarketRoute,
  OpportunitiesRoute: OpportunitiesRouteWithChildren,
  StartupsRoute: StartupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
